setups:
  config-master-1:
    groups:
    - name: gromacs
    actions:
    - type: command
      command: touch master.txt


  config-slave-1:
    groups:
    - name: gromacs
    actions:
    - type: command
      command: touch slave.txt


  prepara-tudo:
    actions:
    - type: action
      name: configure-hosts
      group: gromacs
    - type: action
      name: simulation-setup
      group: gromacs


clusters:
  cluster-t2-micro-2x:
    nodes:
      node-slave:
        type: type-a
        count: 4
        min_count: 4
        setups: 
        - config-slave-1
      node-master:
        type: type-a
        count: 1
        min_count: 1
        setups: 
        - config-master-1

    after:
    - prepara-tudo